### ISSUE TITLE
Change infinite check on feedback to look at front absorber rather than ring current

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1030]
The check in GDA when waiting for Hyperion currently resets the timeout when ring current is less than a certain amount. This is a poor thing to check, we should instead be looking at the front absorber.

**Comment by olliesilvester** [comment]
See https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/40490/4

**Comment by DominicOram** [comment]
Code now merged and tested in beamline, thanks Ollie!
