### ISSUE TITLE
Robot load: Check PinDetect

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1048]
Following https://github.com/DiamondLightSource/hyperion/issues/1234 we can do a robot load. We should now, following it, check that the pin has correctly been loaded.

This can be done by looking at the PinDetected input in the robot load I/O

## Acceptance Criteria
* Hyperion waits for pin detected with a timeout
* If no pin has been detected we should no longer do the centring and pass back to GDA with a warning exception

**Comment by stan-dot** [comment]
[plan link](https://github.com/DiamondLightSource/hyperion/blob/main/src/hyperion/experiment_plans/wait_for_robot_load_then_centre_plan.py)

test [link](https://github.com/DiamondLightSource/hyperion/blob/main/tests/unit_tests/experiment_plans/test_wait_for_robot_load_then_centre.py)


[one other file](https://github.com/DiamondLightSource/hyperion/blob/main/tests/unit_tests/device_setup_plans/test_setup_oav.py) where file detect is tested

**Comment by DominicOram** [comment]
The message should go in the status

**Comment by DominicOram** [comment]
The way I was thinking of implementing this is that the robot load device only sets the return status to True once the pin has been detected. This should mean the plan doesn't need to worry about details of the check

**Comment by DominicOram** [comment]
<0.5 days
