### ISSUE TITLE
Write a full test plan and change notes for next run

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1059]
We have a lot of new features at varying levels of stability in the coming run:
* Change energy
* Rotation scans
* Running Hyperion straight after robot load
* Panda
* Pin tip centring in ophyd?

We need to write a document (and agree it with @neil-i03) on:
* How to turn these features on and off
* The order we want to test them in

**Comment by DominicOram** [comment]
I think we need any local contact to be able to turn them off in case something happens in the middle of the night so I think it might have to be GDA properties.

**Comment by olliesilvester** [comment]
Property to use PandA is added in https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/40851

**Comment by DominicOram** [comment]
Closed by the New Features table in https://confluence.diamond.ac.uk/display/MXGDA/Hyperion+User+Docs
