### ISSUE TITLE
Investigate and avoid overwriting files

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#107]
We have seen in https://github.com/DiamondLightSource/python-artemis/issues/100#issuecomment-1135822750 that if the same run number is used twice the 2nd time can overwrite data from the first. We should guard against this in the following places:
* GDA high level
* Artemis high level
* ODIN
* nexgen

**Comment by dperl-dls** [comment]
This has been addressed with https://github.com/DiamondLightSource/dodal/pull/273
If we still have an issue with overwriting files, a new, more specific issue should be made
