### ISSUE TITLE
Issues found from beamline testing 15/01

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#1072]
- start script always starts in dev mode - addressed in #1079 
- warningexception about moving pin into view doesn't end plan from GDA perspective https://graylog2.diamond.ac.uk/messages/logs_8608/7577a431-b3bd-11ee-873a-1866dafae8e4 - Fixed in GDA
- float rounding error in ispyb comment https://ispyb.diamond.ac.uk/dc/visit/cm37235-1/id/12606774
- error message on zocalo timeout no good (AsyncStatus errored) - should fix this in ophyd-async, and/or bluesky - https://github.com/bluesky/ophyd-async/pull/104

**Comment by DominicOram** [comment]
Fixed 2. with adding a `break` into GDA:
```
				if response["exception_type"] in HYPERION_WARN_EXCEPTIONS:
					update("Warning from Hyperion: %s" % (response["message"]))
					break
```

**Comment by DominicOram** [comment]
Fix in gerrit for the `break` https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/40909
