### ISSUE TITLE
GDA to call wait_for_robot_load_then_centre with the requested energy parameter

### ISSUE THREAD

**Issue by rtuck99** [DiamondLightSource/hyperion#1076]
Following on from #1071 

Currently GDA sets the energy itself and then communicates the current energy value to hyperion with the current_energy_ev parameter.

This needs to be changed so that
* Instead of performing the energy change itself, the desired energy from ispyb is forwarded to hyperion in the wait for robot load request as the requested_energy_kev value. Hyperion then as per #1071 will apply the energy changes, and read back the energy from the DCM PV  and record this in ispyb.
* The current_energy_ev parameter is then removed from the existing GDA logic

**Comment by DominicOram** [comment]
Change now merged so closing this
