### ISSUE TITLE
Use energy as read during collection in ispyb

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1102]
https://github.com/DiamondLightSource/hyperion/pull/1074 adds an energy read during collection but also still adds the energy to the ispyb parameters before collection. If we're reading the energy we no longer need to provide it upfront.

## Acceptance Criteria
* The energy that is read during collection gets put in ispyb
* We no longer set the energy upfront anywhere, including when called from GDA

**Comment by DominicOram** [comment]
This might be already done?

**Comment by rtuck99** [comment]
The energy has been removed already but we still seem to have an undulator gap field which I think can be removed
