### ISSUE TITLE
Modify the deploy script to run on the control machine so that the correct versions of dependencies are installed

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#1103]
RHEL 7 is limited to GLIBC 2.17, which limits pyzmq to <25 for the default wheel. However, there is an `pyzmq-26.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` build which is still compatible, and will be installed if the pip install is run on the control machine instead of a RHEL8(+) machine

### Acceptance criteria:
- deploy script builds the `venv` ssh'd to the control machine
- dependency pin for pyzmq is removed

**Comment by DominicOram** [comment]
Maybe this is a sign we should containerize?

**Comment by DominicOram** [comment]
Lets do the control machine fix for now and think harder about long term solutions

**Comment by olliesilvester** [comment]
See https://github.com/DiamondLightSource/hyperion/issues/1367 for the longer term solution
