### ISSUE TITLE
Issues from testing v8.8

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#1105]
- manual grid scans have wavelength off by x1000 (https://ispyb.diamond.ac.uk/dc/visit/cm37235-1/dcg/11085963)
- with external callbacks enabled, logging issue - graylog messages are not tagged with artemis stream except from `__main__` ?!
- rotation scan needs global param version
- ~~ispyb doesn't seem to be pointing at images (https://ispyb.diamond.ac.uk/dc/visit/cm37235-1/dcg/11086026)~~ nexus files were not being written

**Comment by DominicOram** [comment]
Fixed the first issue:
```python
            self.params.hyperion_params.ispyb_params.current_energy_ev = doc["data"][
                "dcm_energy_in_kev"
            ]
```
should be:
```python
            self.params.hyperion_params.ispyb_params.current_energy_ev = doc["data"][
                "dcm_energy_in_kev"
            ] * 1000
```

**Comment by DominicOram** [comment]
Additionally, we need to increase the time we wait for the FGS parameters to be valid to 0.6s (https://github.com/DiamondLightSource/hyperion/issues/1101)
