### ISSUE TITLE
Weird typos in log messages

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#1154]
`depositrtyrtyion` rather than `deposition` in https://graylog2.diamond.ac.uk/messages/logs_8652/38743030-cc2c-11ee-8ab3-1866dafae904

Not found searching the source

**Comment by olliesilvester** [comment]
Ah, this was me and Rob while debugging yesterday. I did change it back and did a Hyperion restart before this time though, I don't think this is an issue now
