### ISSUE TITLE
Fixes needed for v8.10.0

### ISSUE THREAD

**Issue by olliesilvester** [DiamondLightSource/hyperion#1176]
I found a few issues when testing the new release. I03 is running 8.9.0 now as I didn't figure out the problems in time, but they are:

- The robot's `bare_signal` is type `str`, but when we read it, somewhere it gets converted to numpy's `str_`, so we need to change the type hint back to what it was
- In the new pin image recognition code, we are trying to do a `set_sim_value` on a `soft_signal_r`. This doesn't work because we are connecting to the device with `sim_mode = False`, so the sim backend which it tries to access is never created. We need to use `_backend.put` instead. Ophyd async people are currently working on a supported way to do soft signals, see - https://github.com/bluesky/ophyd-async/issues/94
- The recent logging change means exceptions don't always get logged to files unless the exception is logged in the code. This means  `/dls_sw/i03/logs/bluesky/start_log.txt` doesn't get filled properly

**Comment by DominicOram** [comment]
Given the merged PR fixes the first two issues I'm spinning the last into it's own issue and closing this

**Comment by DominicOram** [comment]
https://github.com/DiamondLightSource/hyperion/issues/1186
