### ISSUE TITLE
UDC shouldn't stop if pin not found

### ISSUE THREAD

**Issue by olliesilvester** [DiamondLightSource/hyperion#1181]
After the recent changes to the pin tip centring plan, UDC stops running if Hyperion can't find the pin tip. Instead, GDA should catch the pin tip centring failure and move onto the the next sample. This is how it behaved previous to v8.10.0. On the GDA side, the list of exceptions caught by Hyperion which don't stop UDC are in `mx-config/scripts/hyperion_utils/exceptions.py`

See https://graylog2.diamond.ac.uk/messages/logs_8662/ae3d51c2-d1a4-11ee-873a-1866dafae8e4 for an instance of UDC being stopped due to Hyperion not finding the pin tip

### Acceptance criteria

- Use a different exception when pin tip failed, GDA catches this and moves to next sample.
- Test this behavior, mocking the GDA part

**Comment by DominicOram** [comment]
Specifically the exception that Hyperion should be wrapping it in is a `WarningException` e.g. like when the pin is too short/long
