### ISSUE TITLE
Log all errors

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1186]
The recent logging change means exceptions don't always get logged to files unless the exception is explicitly logged in the code. This means `start_log.txt` doesn't get filled properly.

## Acceptance Criteria
* Exceptions are logged automatically
* `start_log.txt` gets properly filled

**Comment by olliesilvester** [comment]
Since **https://github.com/DiamondLightSource/hyperion/pull/1137**, exceptions will only go to `start_log.txt` if they get logged in the code. Within the main Hyperion loop, this should always happen. If something breaks before this, it will not.

**Comment by dperl-dls** [comment]
I confess I don't totally understand how the `start_log` works - I had thought it just captured logging output until the logs are setup another way. What is it actually meant to do?

I guess this is actually related to my using `screen` in the startup script and it not propagating the output in the way I thought

**Comment by DominicOram** [comment]
Yes, that's all it's meant to do. If there's an exception on startup due to e.g. an import/syntax error. The logger will not yet be set up so we just need a way to capture it. From the issue description (which I copied from https://github.com/DiamondLightSource/hyperion/issues/1176) it seemed vague on whether this just affected the `start_log` or we were losing errors in general. @olliesilvester or @dperl-dls do you have an idea how much is affected?
