### ISSUE TITLE
Improve logging MemoryHandler and add a REST endpoint to write debug logs

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#1191]
I misunderstood the functionality of `MemoryHandler`, which actually dumps logs whenever the buffer is full (or when an `error` is encountered, as expected). Instead we should replace the buffer list with a deque which doesn't automatically flush when full.

We should add an endpoint to allow manually triggering flushing the debug log in case hyperion hangs without encountering an exception, and maybe add this to the `run_hyperion` script

**Comment by DominicOram** [comment]
Part one is fixed by https://github.com/DiamondLightSource/dodal/pull/352. Part two spun into https://github.com/DiamondLightSource/hyperion/issues/1201
