### ISSUE TITLE
Tidy from change to Ophyd-async edge detection

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#1219]
After https://github.com/DiamondLightSource/dodal/pull/358 and https://github.com/DiamondLightSource/hyperion/pull/1214, the AreaDetector plugin for edge detection is no longer needed; we should remove it from Dodal and any plans which relate to it from Hyperion
- Rename the `PinTipDetection` to something like `EdgeDetection`
- Remove optional MXSC use from hyperion plans
- Remove MXSC from dodal, changing the built in utils which use it
- Remove the parameter that turns this on from Hyperion/GDA

**Comment by DominicOram** [comment]
Mostly tidying tests ~1 day
