### ISSUE TITLE
Grids sometimes to the edge of image

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#1227]
e.g. https://ispyb.diamond.ac.uk/dc/visit/in29352-55/dcg/11425683

**Comment by DominicOram** [comment]
We should look back and count how many times the grid was large recently (maybe just do a histogram of grid heights?). We should also then log the edges, either through logging the array or taking an image.

**Comment by dperl-dls** [comment]
![Figure_1](https://github.com/DiamondLightSource/hyperion/assets/115003895/48bf0a00-891b-4a71-a45e-0a5c1da72f95)
Extracted y_steps from the last two days of logs

**Comment by DominicOram** [comment]
Looks like there are -1's in the edge detection for both top/bottom https://graylog2.diamond.ac.uk/messages/logs_8684/a440f231-dd61-11ee-a034-1866dafadc6c. Maybe filter these out rather than the 0s?
