### ISSUE TITLE
Use ophyd_async synchotron

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1251]
DAQ Core have made us an OA Synchotron (https://github.com/DiamondLightSource/dodal/pull/361) we should use it.

## Acceptance Criteria
* Hyperion uses the OA Synchotron

**Comment by DiamondJoseph** [comment]
We're also implementing other optical components (targetting i22), may be useful (and so we don't duplicate effort)

**Comment by DominicOram** [comment]
Cool, if you link me to the dodal issues that describe each of the components you're moving I'll make corresponding Hyperion issues if required

**Comment by DiamondJoseph** [comment]
https://github.com/DiamondLightSource/dodal/issues/377

May be split into smaller commits but just the one ticket for now
