### ISSUE TITLE
Dodal loggers not initialised in callback process

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1252]
When interacting with zocalo we log into the dodal logger. However, this is being done in the callback process. It looks like the dodal loggers are not initialised in this process and so logs inside e.g. `zocalo_interaction` are not getting logged to graylog.

## Acceptance Criteria
* Logs in `zocalo_interaction` are correctly sent to graylog etc.

**Comment by DominicOram** [comment]
We think XS/S

**Comment by rtuck99** [comment]
Reopened as unit test failures started happening

**Comment by DominicOram** [comment]
Now fixed by https://github.com/DiamondLightSource/hyperion/pull/1288
