### ISSUE TITLE
Modify the callbacks to use the new external param classes

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#1276]
See https://github.com/DiamondLightSource/hyperion/issues/1092 and https://github.com/DiamondLightSource/hyperion/issues/1275

## Acceptance Criteria
* The callbacks use the new parameters and have no dependency on the old models
* Tests all pass
* In doing this think about callback structure, what parameters it needs and spin out new issues if there are ways to simplify

**Comment by DominicOram** [comment]
Depends on https://github.com/DiamondLightSource/hyperion/pull/1279 and https://github.com/DiamondLightSource/hyperion/issues/698

**Comment by DominicOram** [comment]
We think a M
