### ISSUE TITLE
Make a plan to fill current beamline state into recieved params

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#1286]
Following #698 We want some parameters to be optional to pass to Hyperion (e.g. `detector_distance`, energy...) and just use the current beamline state for these. Currently these are typed as optional but are required to be passed in in order to generate `DetectorParams`, etc. There should be a generic plan which takes a recieved parameters object, and based on its mixins and which fields are none, fills in missing values.

**Comment by DominicOram** [comment]
@DominicOram do we need this?
