### ISSUE TITLE
Remove now obsolete references to transmission_fraction and flux

### ISSUE THREAD

**Issue by rtuck99** [DiamondLightSource/hyperion#1295]
Since the integration of PRs to fix #1733 ~and #1033~ we can now remove the code referenced by the corresponding TODOs and also remove the ispyb_params fields

#1033 current energy covered by #1292

**Comment by DominicOram** [comment]
Sorry, my bad for making awkward half issues. This makes sense to do as one with https://github.com/DiamondLightSource/hyperion/issues/1292 so putting it all in there.
