### ISSUE TITLE
Refactor nexus writer code to work with new versions of nexgen 

### ISSUE THREAD

**Issue by noemifrisina** [DiamondLightSource/hyperion#1321]
In [nexgen#220](https://github.com/DiamondLightSource/nexgen/pull/220), a lot of the module names have been refactored, which means 
`src/hyperion/external_interaction/nexus/write_nexus.py` and `src/hyperion/external_interaction/nexus/nexus_utils.py` 
need to be refactored to reflect this change in order to keep working for versions of `nexgen` newer than `0.8.7`.

Until this is done, we should keep the pinned version to `nexgen==0.8.7`.

**Comment by dperl-dls** [comment]
The linked PR updates hyperion so that it will be compatible with a new release of Nexgen
