### ISSUE TITLE
Panda: Write positions for every gridscan

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1339]
As a scientist/developer I would like to know that the panda is triggering at the right places. The panda can write triggering positions out as HDF files, we should configure it so that it always does this.

Note:
* We provided the panda with a directory for this at https://github.com/DiamondLightSource/hyperion/pull/1337 but that directory will not exist, we may need to create it

## Acceptance Criteria
* Every time a panda grid scan is run it writes the positions out to an appropriate file

**Comment by olliesilvester** [comment]
I just tried this out and we _will_ need to create the directory first

**Comment by olliesilvester** [comment]
The deployed Hyperion version now uses the directory provider, but we aren't creating the panda directory anywhere, so we need to make sure it's created in Hyperion before the next release
