### ISSUE TITLE
Nexus file cannot be read by `imginfo`

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1350]
Nexus files being written by the latest Hyperion version cannot be parsed by `imginfo`. To reproduce the error see https://diamondlightsource.slack.com/archives/C048RD0KFFF/p1715011760143679?thread_ts=1714765475.230639&cid=C048RD0KFFF

## Acceptance Criteria
* `imginfo` passes on all nexus files written by Hyperion
* There is an automated test that confirms nexus files can be read by imginfo

**Comment by DominicOram** [comment]
Discussed with @dperl-dls - we could build the docker container as part of `dev_dls_env` and so quickly run the tests locallys

**Comment by dperl-dls** [comment]
Possible that https://github.com/DiamondLightSource/nexgen/pull/224 caused some of these issues where there is a mismatch between the `_master.h5`/`.nxs` file and the `meta.h5`
