### ISSUE TITLE
Calculate resolution if not passed in

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1359]
Currently the rotation and XRC plans rely on GDA to pass resolution in for us to put in ispyb. Hyperion should be able to calculate this itself, in fact it does so in `robot_load_then_centre`. This calculation may make sense to do in the callback?

To caclulcate the resolution we need to read various parameters on the beamline and we need to make sure to do them after they are set up for data collection.

## Acceptance Criteria
* Hyperion calculates resolution itself for XRC/rotations based on the state of the beamline during the collection
* Resolution is removed as something that can be passed into hyperion

**Comment by dperl-dls** [comment]
We only use this for ISPyB so the logic should live in the callback - we just read the prerequisite in the plan

**Comment by DominicOram** [comment]
* When reading hardware for ispyb during collection we read everything this needs
* Ispyb callback then does the calc (using existing function, puts it into ispyb
* Remove the calculation from robot load and resolution in ispyb params
* Medium
