### ISSUE TITLE
Make sure data directory matches GDA format exactly

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#1362]
The storage directory is now calculated by hyperion instead of GDA, we need tests to make sure it stays the same to avoid causing issues for users whose scropts might rely on those path patterns.

**Comment by DominicOram** [comment]
Medium

**Comment by rtuck99** [comment]
The current behaviour is that the directory is explicitly specified in the `storage_directory` parameter; this is mapped to the `detector_params.directory` attribute and we don't currently do any computation on it.
It seems to be adequately covered by tests as far as hyperion logic goes, judging by what breaks if you bodge `detector_params.directory` to return a different value, although I don't think the tests are particularly explicit.

**Comment by DominicOram** [comment]
I think I agree that this is fine. Thank you
