### ISSUE TITLE
Make a properties/configuration service

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#1397]
which we can query for:
- "should we use GPU or traditional XRC results"?
- "should we set the stub offsets"
- beamline parameters (will remain file-based for now)
- etc.?

**Comment by DominicOram** [comment]
As discussed. MVP for this is:
* A service run in central K8s
* Service backed by a redis database
* A REST interface on this service to get/set feature flags of:
   * Use panda
   * Panda run up distance
   * Use GPU
* Hyperion able to get values from this service
* If the service is unavailable Hyperion logs an ERROR but defaults back to turning the feature off and continues anyway
