### ISSUE TITLE
Panda gridscan issues discovered during testing of 9.5.2

### ISSUE THREAD

**Issue by rtuck99** [DiamondLightSource/hyperion#1517]
Fix the following issues discovered during testing:
* Panda prescale was not set so pulses were wrong width - Fixed by #1515
* Panda sequencer pulse width should be set so that PCAP sampling window corresponds to the exposure window
* Panda directory provider is providing the wrong directory name ("panda/panda" instead of just "panda")
* Panda capture file name should be unique instead of just "panda.h5"

**Comment by DominicOram** [comment]
Some of these might be covered by changes cherry-picked off the beamline at https://github.com/DiamondLightSource/hyperion/pull/1515/files
