### ISSUE TITLE
Move FGS into smargon

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#155]
As of https://github.com/DiamondLightSource/python-artemis/pull/112 we have both a `Smargon` device and an `FastGridScan` device. We should move the `FastGridScan` one to be a sub device of the `Smargon` to match the IOC

**Comment by evalott100** [comment]
I've done this by having fast_grid_scan as a variable in I03Smargon.

We should rethink where the I03Smargon class should go - using it in motors.py is problematic as the is_valid function in fast_grid_scan.py uses the XYZLimitBundle class as a type for the limits positional variable, which can't be imported from motors.py without a circular import error.

**Comment by dperl-dls** [comment]
Closing as stale - should be reopened in Dodal repository if still relevant
