### ISSUE TITLE
Flux calculation

### ISSUE THREAD

**Issue by npat113** [DiamondLightSource/hyperion#207]
From GDA I would like to use the flux calculations that @npat113 has added in 207-Flux.

To get these working in GDA we need to:
* Take the work Neil has done and add some tests/tidy up if required
* Add a new endpoint in Artemis that calls these plans
* Update docs appropriately
* Modify GDA to instead call Artemis

**Comment by npat113** [comment]
Code functional. Branch 207-Flux.

**Comment by DominicOram** [comment]
Flux is now being calculated in the EPICS layer so this is not required
