### ISSUE TITLE
Review Blocking Code in Plans

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/hyperion#323]
As discussed with @DominicOram and @dperl-dls, the Artemis plans currently contain long-running blocking code, such as waiting for results from Zocalo. 
This makes offline mocking difficult and potentially doesn't play well with asyncio. Ideally we would like a solution involving Bluesky messages. Something along the lines of:

```python
yield from bps.wait("zocalo")
```

This issue is for reviewing possible solutions and places where they may be needed in existing code.

**Comment by DominicOram** [comment]
See also https://github.com/DiamondLightSource/python-artemis/issues/597

**Comment by DominicOram** [comment]
I think we can probably get the callback to return a `Future` and so use `bps.wait_for`
