### ISSUE TITLE
Make fake zocalo play nice with dummy GDA

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#383]
Currently there are clashes between the activemq instance that dummy GDA needs and the rabbitMQ instance for fake_zocalo. Can they use the same instance or can we have some good scripts for cleaning them both up sufficiently?

**Comment by dperl-dls** [comment]
The current fake zocalo script nicely shuts down activemq if necessary, and the rabbitmq closes when we stop using fake zocalo. this doesn't seem to be causing much of a problem, therefore.
