### ISSUE TITLE
Put system tests in CI

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#459]
Until system tests are in CI they're going to be ignored. To get them running in CI we need to do the following:
- [x] https://github.com/DiamondLightSource/python-artemis/issues/458
- [x] Create a script that starts up all our system test environment locally using both the above
- [x] Set up a cronjob to run this script
- [x] Get it to email developers / slack (whichever is easiest) with the results

**Comment by DominicOram** [comment]
We discussed this with DAQ core, plan is to use @dperl-dls's old machine as a Jenkins node

**Comment by DominicOram** [comment]
We think about 3 days

**Comment by dperl-dls** [comment]
Do you think that the scripts etc. for this belong in the Hyperion repo?

**Comment by dperl-dls** [comment]
A basic setup to locally run the system tests in an automated fashion is now at https://gitlab.diamond.ac.uk/MX-GDA/hyperion-system-testing

New issues should be made for further improvements
