### ISSUE TITLE
Remove experiment type from external parameters

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#643]
Currently the external API has an endpoint per plan type but also expects a field with the plan type. This is redundant and we should remove the field.

## Note
* We should remove it externally, if it's useful to keep internally that's fine
* This may be affected by https://github.com/DiamondLightSource/python-artemis/issues/31

**Comment by dperl-dls** [comment]
can be part of #698

**Comment by DominicOram** [comment]
Removed as part of linked issue
