### ISSUE TITLE
Handle multipin

### ISSUE THREAD

**Issue by npat113** [DiamondLightSource/hyperion#693]
Multipins will require special handling from Artemis and the optical tip centring routine. We need a way of specifying the pin type when loading a sample.

Current offset for tip centring is 50microns, this needs altered to 900 microns for multipin (value may change slightly from this depending on final multipin design). 

The X cap on grid size also needs changed to 2200mm (again, subject to change).

This whole process will operate at zoom 1 and in flatfield mode.

**Comment by DominicOram** [comment]
Still doing edge detection
Will need to do tip centring in Hyperion

**Comment by DominicOram** [comment]
Initial tests done on the `multipin_tests` branch in `bluesky/artemis_v5.1.0`. Drew an apparently correct grid (https://ispyb.diamond.ac.uk/dc/visit/cm33866-3/dcg/9787083) didn't get any further as need crystals on the pin.

**Comment by DominicOram** [comment]
More testing on 20/07/23

**Comment by DominicOram** [comment]
Put the centres in motor positions in the ispy comment

**Comment by DominicOram** [comment]
https://github.com/DiamondLightSource/python-artemis/issues/828 is script for the hacky GDA integration

**Comment by DominicOram** [comment]
Hyperion side covered in https://github.com/DiamondLightSource/hyperion/pull/852, GDA side in https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/39819

**Comment by DominicOram** [comment]
Just waiting on https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/39822

**Comment by DominicOram** [comment]
Associated gerrit change is merged, closing this
