### ISSUE TITLE
improve external parameters and make pydantic models for them

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#698]
to replace the JSON schema for validation
as part of this, the external parameter structure should be improved, to remove references to ISPYB etc
possibly depends on getting some values from hardware

**Comment by DominicOram** [comment]
At the same time deal with the fact we have the version defined in the schema and constants

**Comment by dperl-dls** [comment]
from https://github.com/DiamondLightSource/python-artemis/pull/757
This should include:
- rotation start angle instead of `omega_start`
- get rid of unused `upper_left`,`position`?

**Comment by DominicOram** [comment]
For `position` we can just read this out of the hardware

**Comment by DominicOram** [comment]
Additionally I don't think `microns_per_pixel` is needed for rotation scans

**Comment by dperl-dls** [comment]
This should be done before #964 to make that easier

**Comment by DominicOram** [comment]
Could think about https://github.com/DiamondLightSource/hyperion/issues/1018 at the same time

**Comment by dperl-dls** [comment]
This will now be step one of https://github.com/DiamondLightSource/hyperion/issues/1092
