### ISSUE TITLE
Set Energy

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#782]
Hyperion will need to set energy on the beamline.

## Acceptance Criteria
* We understand how energy is changed from GDA - a document is created to describe it
* Discuss this with the scientists
* We have a dodal device + basic plan that can change beamline energy

**Comment by DominicOram** [comment]
Pitch lookup doesn't do good interpolation currently (chat to @neil-i03 when we get to this point)

**Comment by DominicOram** [comment]
Need to do #795 as part of this so do it first

**Comment by DominicOram** [comment]
From @neil-i03 's head (we should check GDA) - should be able to do simultaneously:
* Turn off feedback
* Change gap - if required (based on lookup table)
* Change the bragg/energy on the mono
* Apply lookup table value for pitch/roll
* Apply mirror strip/voltages
* Turn feedback on and wait to stabilise

**Comment by rtuck99** [comment]
See [https://github.com/DiamondLightSource/hyperion/wiki/Beamline-Energy-Implementation]() for description of the current GDA implementation of beamline energy setup

**Comment by DominicOram** [comment]
Waiting on #1071

**Comment by DominicOram** [comment]
All child issues are done so now closing this but it needs further testing https://github.com/DiamondLightSource/hyperion/issues/1202
