### ISSUE TITLE
Document plans better

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#787]
With a few different plans now we need a standard set of documentation that gives:
* What the plan does exactly
* What parameters it expects to be passed in

We should probably build these docs automatically from docstrings in the code.

**Comment by DominicOram** [comment]
Maybe some diagrams of "this plan calls this one" etc. will also be useful

**Comment by npat113** [comment]
Also where is it reading the parameters from - when we come to removing the GDA sprawl of parameter files this will be very useful

**Comment by DominicOram** [comment]
As part of this also sit down with @npat113 and @ndg63276 to discuss the structure of the project and walk through the documentation

**Comment by DominicOram** [comment]
@npat113 asked today where the logic for selecting aperture sizes lives, this should also be in this documentation

**Comment by DominicOram** [comment]
Initial work at https://github.com/DiamondLightSource/hyperion/wiki/Code-Map. This should cover where the logic lives but not the parameters part yet. @npat113, @noemifrisina and @olliesilvester, you all asked me about this sort of stuff, does this documentation answer your questions?

**Comment by olliesilvester** [comment]
Plan overviews and order of operations are really useful thanks!

**Comment by DominicOram** [comment]
Discussed in person with @noemifrisina and @npat113, they're happy with it but still need to do parameters.
