### ISSUE TITLE
system tests are broken

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#818]
Several recent changes in artemis, including adding new devices, have not been reflected in the system tests

**Comment by DominicOram** [comment]
Needs everyone to sit down and take a look at this together

**Comment by DominicOram** [comment]
@DominicOram review this with a view to get it merged ASAP

**Comment by DominicOram** [comment]
Closing as we merged associated issue. I think make new issues to fix any specific problems
