### ISSUE TITLE
Signify on synchweb pin too long/short due to pin detect

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#824]
After https://github.com/DiamondLightSource/python-artemis/issues/499 we will not be doing a grid scan at all if the pin is too/short long and so not registering a grid collection in ispyb. Previously when the pin was too long/short we signified this to the user by putting the grid collection in ispyb with an error state and a comment saying the error. Given that we're not registering a grid at all now we need a different way of informing the user.

## Acceptance Criteria
* On pin too long/short there is a clear indication to the user in synchweb

**Comment by DominicOram** [comment]
The first place to try putting it is the rotation collection comment but this will require some GDA work. Ultimately we will skip the rotation as well so it might be better to put it in the robot load?

**Comment by DominicOram** [comment]
* Talk to synchweb if there are other ways to do this - define an experiment kind called error? Maybe @ndg63276 can help

**Comment by ndg63276** [comment]
The RobotAction table has a `status` field, which can be `WARNING`, might be the most suitable.

**Comment by DominicOram** [comment]
Hmm... That doesn't feel great because it's not really an issue with the robot load but a subsequent issue. Might be the simplest solution for now though

**Comment by DominicOram** [comment]
https://github.com/DiamondLightSource/hyperion/issues/996 is related

**Comment by DominicOram** [comment]
In the latest version we should get an error on the XRC entry. Confirm this and close the issue if we do.

**Comment by dperl-dls** [comment]
- this basically just means adding to the ispyb comment on pin too long/short
- we may get this for free?
- work here is to confirm it is working; if it isn't, do it

we think small

**Comment by DominicOram** [comment]
We do not currently get this for free as the warning comes out of pin tip detection and we don't add the callback until we send `GRID_DETECT_AND_DO_GRIDSCAN` later. To fix we probably want to move `GRID_DETECT_AND_DO_GRIDSCAN` to earlier
