### ISSUE TITLE
Tidy up tests and fixtures

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#837]
Currently we are duplicating a lot of test fixtures and setup between different modules, someone should go through and clean it all up.

Eg:
comments on https://github.com/DiamondLightSource/python-artemis/pull/757 should be extended to just have one, multifunctional, smargon for unit testing

**Comment by DominicOram** [comment]
A lot of the fixtures are trying to fake some logic on the device. https://github.com/DiamondLightSource/dodal/issues/98 probably comes into this
