### ISSUE TITLE
Add bluesky plan support for PandA

### ISSUE THREAD

**Issue by olliesilvester** [DiamondLightSource/hyperion#870]
In order to get a PandA working on I03, Hyperion will need to have the option to use an Ophyd PandA device in its plans instead of the Zebra 1

Related dodal issue is https://github.com/DiamondLightSource/dodal/issues/117

**Comment by DominicOram** [comment]
We need a property to be able to switch between panda vs old FGS
Two plans, one for zebra + old FGS program and one for panda + new FGS program

**Comment by DominicOram** [comment]
To do the test (for now):
* Add the plan into the experiment registry
* Create a new `panda_test_params.json` based on `test_params.json` with some good fixed default values
* For live testing use https://github.com/DiamondLightSource/hyperion#starting-a-scan (you will need to be `ssh`'d into the control machine

**Comment by DominicOram** [comment]
Waiting on https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/40851 to merge

**Comment by DominicOram** [comment]
Given we've been running various PandA tests I'm happy to call this done
