### ISSUE TITLE
Do not accept non-integer FGS dwell times

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#895]
We think the FGS program will not accept a non-integer dwell time. When setting we should throw an error if this has not been set correctly

## Acceptance Criteria
* Throw an error in the pydantic params
* Throw an error in the FGS ophyd device

**Comment by subinsaji** [comment]
We should do this in `dodal` and override the `set`/`put` (whichever is lowest) of the FGS dwell_time to round values. Alternatively look at check_value in ophyd. Alternatively, alternatively, is this easier in ophyd-async?

**Comment by DominicOram** [comment]
Fixed with https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/40021 temporarily
