### ISSUE TITLE
move_pin_into_view moves out of smargon x limits

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#906]
when the pin is too long 'move_pin_into_view' moves out of the smargon x limit during OAV centring

https://ispyb.diamond.ac.uk/dc/visit/mx32736-17/id/11772912
https://graylog2.diamond.ac.uk/messages/logs_8415/81e663d1-5d84-11ee-ae6d-1866dafadc6c

we should check the limits and raise a warningexception to exit the experiment gracefully

**Comment by DominicOram** [comment]
I think the smargon x should always be at 0 at this point, we should double check logs whether GDA was doing pin tip centring and making it non-zero
