### ISSUE TITLE
Flux is not being read from the hardware

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#913]
Due to a bug in https://github.com/DiamondLightSource/hyperion/issues/632 we're actually still using the GDA provided flux, rather than reading it from the hardware. You can see this if you change `flux_test_value` in `test_read_hardware_for_ispyb_updates_from_ophyd_devices` to be any value other than 10.0

**Comment by subinsaji** [comment]
Reopened this issue so I can call a single dictionary instead of being there 3 times as discussed here https://github.com/DiamondLightSource/hyperion/pull/917#discussion_r1346173700
