### ISSUE TITLE
Failed to move to find tip

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#924]
For collection https://ispyb.diamond.ac.uk/dc/visit/mx33658-16/dcg/10470342 Hyperion should have moved `x` around to try and find the tip, it didn't. From the logs it looks like Hyperion thought it found a tip. We should:

* Add more logging
* Watch out for this happening again, if it does look into averaging tip detection amongst more frames

**Comment by DominicOram** [comment]
We have seen this a couple of additional times when running overnight

**Comment by DominicOram** [comment]
https://ispyb.diamond.ac.uk/samples/sid/5003238 initially found a tip at (608, 360) but then couldn;t find the loop. We could also fix this by tweaking the edge detection settings. Suggest we find some time in shutdown to leave the edge detection on with no pin then see if we can catch when it gives a false positive

**Comment by DominicOram** [comment]
Good solution will be wait until the pin tip is "stable"

**Comment by dperl-dls** [comment]
@dperl-dls waiting on ophyd2 oav stuff

**Comment by DominicOram** [comment]
Hotfix in https://github.com/DiamondLightSource/dodal/pull/242 works fine for now, let's call this done
