### ISSUE TITLE
Handle beam dumps

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#927]
In usual operations when the beam is dumped we want to do all operations possible until collection and then wait for the beam to come back. In GDA this is done by waiting forever on the feedback on the xbpm before collection. Currently, this doesn't work because there is a timeout in GDA for how long Hyperion should take overall.

## Acceptance Criteria
* We discuss the best way to do this in Hyperion
* We implement the solution

**Comment by DominicOram** [comment]
As discussed with @callumforrester, a good way to do this would be to periodically update the feedback status with something saying "I'm still waiting", this should already be automatically put on the message bus by `blueapi` (https://github.com/DiamondLightSource/blueapi/blob/main/src/blueapi/worker/event.py#L46C3-L46C3). We can then have a timeout on GDA that we do not get these events periodically. Alternatively/additionally we could look at using suspenders.

**Comment by DominicOram** [comment]
GDA should check ring current if Hyperion timed out. Or front end absorber or XBPM feedback?

**Comment by dperl-dls** [comment]
See Gerrit change: https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/40490

**Comment by olliesilvester** [comment]
In `hyperion_connection`we need to: 

- return None `if response["exception_type"] in HYPERION_WARN_EXCEPTIONS:`
- Change the timeout from 50 to 200
- Remove the timeout from `xbpm_feedback` trigger function (in hyperion)

**Comment by olliesilvester** [comment]
Closed in favour of https://github.com/DiamondLightSource/hyperion/issues/1030
