### ISSUE TITLE
Discussion: How to decide which aperture is selected

### ISSUE THREAD

**Issue by olliesilvester** [DiamondLightSource/hyperion#948]
There is logic in `ophyd` to set aperture positions based on the GDA properties. There is also logic in EPICS to work out with aperture is selected for the the flux, based on different values that may be out of sync with the GDA properties:
![image](https://github.com/DiamondLightSource/hyperion/assets/10086797/1cf28dc8-5110-4403-8400-d55efd0f1065)
We should come up with a unified way of doing this. I04 has the same issue so we should talk to @aragaod too

**Comment by DominicOram** [comment]
Scientists use the properties rather than this PV so can't change this now

**Comment by DominicOram** [comment]
@neil-i03, feel free to add some initial thoughts to this. I'm not too fussed about what the final solution except that keeping track of it in multiple places is going to trip us up at some point

**Comment by aragaod** [comment]
Chicken and egg situation. Scientists (i04) would like to move to the PV but need to move on both the "old" GDA and the new ophyd devices at once. Maybe I create a Jira ticket for GDA to start the gda migration first....

**Comment by DominicOram** [comment]
The ophyd device is now using the PVs from the flux calculator to work out which position we're in. I think this is a good solution as it maintains one source of truth.
