### ISSUE TITLE
Write up learning from I04

### ISSUE THREAD

**Issue by olliesilvester** [DiamondLightSource/hyperion#952]
- Add i04 entry to BEAMLINE_PARAMETER_PATHS to `constants.py`, eg `"i04": "/dls_sw/i04/software/gda_versions/gda_9_29/workspace_git/gda-mx.git/configurations/i04-config/scripts/beamlineParameters"`
- Get an ISPBYB_CONFIG_PATH for i04 in `run_hyperion.sh`
- Reading I04's GDA beamline_parameters currently errors as it tries to set a list as a float. 
- I03 and I04 use different device classes for xbpm_feedback, but hyperion expects the same device for both
- The deploy script needs to have i04 as a recognised beamline. We also need to remove the "remove this" part on line 73

- We needed to add the `gda.gridscan.hyperion` options to gda, copied from the i03 config
- We needed to add `from hyperion_gridscan.hyperion_grid_scan import hyperion_restart` into gda i04-config/scripts

During testing, Hyperion got as far as Odin waiting for all frames to be collected. The number of frames we got was `X_NUM_STEPS * Y_NUM_STEPS`, while the code expected it to be `X_NUM_STEPS * Y_NUM_STEPS + X_NUM_STEPS Z_NUM_STEPS`. The fast grid scan motion program for i03 and i04 are different, so making this consistent is probably the next step

**Comment by DominicOram** [comment]
> * Add i04 entry to BEAMLINE_PARAMETER_PATHS to constants.py, eg "i04": "/dls_sw/i04/software/gda_versions/gda_9_29/workspace_git/gda-mx.git/configurations/i04-config/scripts/beamlineParameters"
> 
> * The deploy script needs to have i04 as a recognised beamline. We also need to remove the "remove this" part on line 73

Can you do these two as part of this issue?

> * Get an ISPBYB_CONFIG_PATH for i04 in run_hyperion.sh
> 
> * Reading I04's GDA beamline_parameters currently errors as it tries to set a list as a float.
> 
> * I03 and I04 use different device classes for xbpm_feedback, but hyperion expects the same device for both

Can you make separate issues for each of these with as much detail as possible

> During testing, Hyperion got as far as Odin waiting for all frames to be collected. The number of frames we got was X_NUM_STEPS * Y_NUM_STEPS, while the code expected it to be X_NUM_STEPS * Y_NUM_STEPS + X_NUM_STEPS Z_NUM_STEPS. The fast grid scan motion program for i03 and i04 are different, so making this consistent is probably the next step

Can you make controls tickets on JIRA for this?

**Comment by olliesilvester** [comment]
Closing as separate issues for these points have been made
