### ISSUE TITLE
Reading I04's GDA beamline_parameters currently errors as it tries to set a list as a float

### ISSUE THREAD

**Issue by olliesilvester** [DiamondLightSource/hyperion#955]
When running Hyperion on I04, `/hyperion/parameters/beamline_parameters.py` reads GDA's 
`/i04-config/scripts/beamlineParameters` and reads in some of the parameters as a float. This errors when these parameters are in a list format (eg the `flux_predict_polynomial_coefficients` parameters so we need a way to handle this.

**Comment by DominicOram** [comment]
We should:
* Handle the list in that file
* Log a warning if there's some other line in the file we can't handle but carry on anyway
