### ISSUE TITLE
Perform multiple rotations in one detector arm

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#960]
As a scientist I would like to speed up doing one rotation followed by another one, e.g. for multipin or for mulitple chi sweeps. One way we can speed things up is to do multiple rotation scans with one detector arm.

## Acceptance Criteria
* There is a plan that can do multiple rotation scans with one detector arm
* The nexus writer will correctly make multiple files (@graeme-winter said he may be able to do the nexgen side of this if it requires a lot of effort)
* The collections are all stored correctly in ispyb but in one group, probably covered by https://github.com/DiamondLightSource/hyperion/issues/920

## Note
* For now need to think too much about the optimum way to move between scans or optimising timing the zebra arm, just get a proof of principle

**Comment by DominicOram** [comment]
For the first try of this, it's fine to rewind omega between collections

**Comment by dperl-dls** [comment]
Notes from testing (version from PR above)

- zocalo callback not triggered right: https://graylog.diamond.ac.uk/messages/graylog-daq-mx-hyperion_21/ef3ee7e0-3aba-11ef-937c-2ae9b41e6ed4
- sample moved with no x/y/z specified?
- needs endpoint exposed

**Comment by DominicOram** [comment]
Needs more testing but review for code quality
