### ISSUE TITLE
Speed up test_pin_tip_centring.py

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#973]
As a developer I would like the unit tests to run as quickly as possible. Currently, when I run the tests with `pytest -m "not s03"` tests in `test_pin_tip_centring.py` takes a noticeable amount of time compared to other files.

## Acceptance Criteria
* Tests in `test_pin_tip_centring.py` still test the same functionality but run faster

**Comment by subinsaji** [comment]
Slowest tests that may need to be sped up:
![Screenshot from 2023-12-06 10-48-29](https://github.com/DiamondLightSource/hyperion/assets/72819027/f3e45129-0773-4b40-9578-a8273e079fcb)
