### ISSUE TITLE
Panda testing notes

### ISSUE THREAD

**Issue by olliesilvester** [DiamondLightSource/hyperion#979]
There are a few remaining tasks left for adding the PandA:

- Refactor panda grid scans to use some common code with regular fast grid scans
- Give an optional input parameter for Hyperion to decide whether or not to use the panda
Then we should do some manual testing to confirm everything still works after the refactor, then we can start to use it with real samples.

**Comment by DominicOram** [comment]
Closing this as the second part is definitely done. First still to do but I think covered elsewhere
