### ISSUE TITLE
Tasks between robot load and gridscan (not including robot load)

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#984]
GDA does a bunch of stuff between robot load and starting a grid scan, not all of which is necessary. Need to:
- look at which steps are required
- implement those

**Comment by DominicOram** [comment]
Plan is to monitor the interlock for when we can move the smargon and start doing the pin tip centring as soon as we can after that. To make sure we don't accidentally crash the smargon into the robot we should remove the gripper from it for doing these tests and set the speed to slow.

**Comment by DominicOram** [comment]
From discussion with @ndg63276, the PV to monitor is `BL03I-MO-SGON-01:DISABLED`, which should be low to be able to move. There are also sufficient interlocks on the beamline that slowing the robot/removing the gripper is not required.

**Comment by DominicOram** [comment]
I've put some code on the beamline that will wait for this and then do a centre. Untested, will test asap

**Comment by DominicOram** [comment]
We probably want to trigger this just before `startLoadAndWaitForPinOrSample` in `sample_control.py` in GDA. We will then need https://github.com/DiamondLightSource/hyperion/issues/1017, some of the info for this can come from GDA, some will need to be provided by Hyperion, specifically the end time and the after snapshot. 

If we assume happy path for these tests then we can probably ignore:
* Robot errors
* Pin detection
