### ISSUE TITLE
Set energy change: Turn off feedback

### ISSUE THREAD

**Issue by rtuck99** [DiamondLightSource/hyperion#985]
As part of https://github.com/DiamondLightSource/hyperion/issues/782, Hyperion needs to disable and re-enable the XBPM feedback before doing any alignment. GDA handles this as follows:

- Checks Beam Position Feedback (BPFB) is available - this looks to be hard-coded for I03
- Sets BL03I-EA-FDBK-01:FB_PAUSE to Pause / Unpaused

We should also add the function to turn feedback back on. as part of this issue

**Comment by rtuck99** [comment]
It looks like we already have code to do this in hyperion.

dodal has `pause_feedback` EpicsSignal in `xbpm_feedback`, `device_setup_plans/xbpm_feedback.py` wraps a pause/unpause together with restoring/applying the attenuator setting at the end in the `transmission_and_xbpm_feedback_for_collection_wrapper`

This is currently used inside `flyscan_xray_centre_plan`  via the `transmission_and_xbpm_feedback_for_collection_decorator`

**Comment by olliesilvester** [comment]
Closing as functionality is already included in xbpm dodal device
