### ISSUE TITLE
Unit test failing: test_grid_detection_plan_runs_and_triggers_snapshots

### ISSUE THREAD

**Issue by rtuck99** [DiamondLightSource/hyperion#998]
The unit test test_grid_detection_plan_runs_and_triggers_snapshots fails with the following message:

FAILED tests/unit_tests/experiment_plans/test_grid_detection_plan.py::test_grid_detection_plan_runs_and_triggers_snapshots - AssertionError: assert 0 == 6

**Comment by dperl-dls** [comment]
This was resolved at some point
